version: '3.4'

services:
  functional-ts:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${SERVER_PORT}
      - TODOS_API_URL=${TODOS_API_URL}
